### ISSUE TITLE
Move models out of the repository

### ISSUE THREAD

**Issue by dustinlacewell** [storybro/storybro#1]
Right now, the models get added into the respository and then git wants manage them. We could add them to the .gitignore but I think it is cleaner to just rework things so that the models are looked for in a more reasonable place; either at the root of the repository in some .gitignored directory, or outside of the repository all together.

We should make this based on an environment as well.

**Comment by dustinlacewell** [comment]
These are the two places the current model path is hardcoded:

```
download_model.sh
6:MODELS_DIRECTORY=generator/gpt2/models

generator/gpt2/gpt2_generator.py
25:        self.model_dir = "generator/gpt2/models"
```

**Comment by machiavel23** [comment]
that's not hardcoded at all. it's just a variable you can edit whenever you want... besides, .sh files can be opened with a basic text editor... I guess I'm gonna bookmark your "fork", I need laugh material.

**Comment by WAUthethird** [comment]
> that's not hardcoded at all. it's just a variable you can edit whenever you want... besides, .sh files can be opened with a basic text editor... I guess I'm gonna bookmark your "fork", I need laugh material.

Seems you don’t understand what hardcoded actually means. In this instance it means a path that’s built into the code, and cannot be changed through the front-end interface. Though it is indeed a variable we can edit, you can currently only edit this variable by changing the code itself, which is not optimal.

**Comment by machiavel23** [comment]
then instead of pointing the paths of a perfectly editable file, show the ACTUAL problematic code. geez, learn to work properly or you won't get far, misleading people like that.

edit: I must be a VIP for a mod leader to pop in as soon as I arrived, I'm kinda blushing

**Comment by dustinlacewell** [comment]
Models root can now be specified by config file, environment variable or cli flag and defaults to `~/.local/share/storybro/models/`. The used model can also be specified in a similar way and defaults to `official_v5`.
