### ISSUE TITLE
Update Tensorflow

### ISSUE THREAD

**Issue by dustinlacewell** [storybro/storybro#2]
Currently we use 1.15 which is quite old.

It also has a packaging bug which prevents us from specifying it as a dependency with Python Poetry: 

https://github.com/python-poetry/poetry/issues/1330

https://github.com/tensorflow/tensorflow/pull/32758

Fixed in https://github.com/tensorflow/tensorflow/releases/tag/v2.1.0-rc2

**Comment by WAUthethird** [comment]
Fixed in #28
